### ISSUE TITLE
Unkeyed hash for "MAC"

### ISSUE THREAD

**Issue by inkeliz** [AugustoResende/RaiLightWallet#10]
The AES-CBC not guaranty the integrity of the message, it allows an attacker to temper the message, without have the knowledge of the plaintext.

The solution for that used in https://github.com/AugustoResende/RaiLightWallet/blob/master/src/js/Wallet.js#L1161 not seems correctly. It is like MAC-And-Encrypt[1], which can be dangerous. The MAC is not a MAC itself, since they don’t have any key[2]. Since not have a key, it can leak the information about the plaintext more easily, it’s theoretical. _It also seens to be similar to plain-hash-then-encrypt[3]._ 

Also, without any key the attacker could guess the original content. Let's suppose that the attacker not have knowledge of the key used in AES, he can guesses the message, possibly using the checksum to confirm the guess.

I think the solutions is:
A)	Replace AES-CBC by AES-GCM, which have GMAC using the tag.
OR
B)	Replace Blake2b by Blake2b Keyed Hashing (MAC/PRF), as described here [4].

The MAC key can be retrieve by the PBKDF2 result, so is possible to use 256 bits of PBKDF2 exclusively for the MAC.

[1] https://crypto.stackexchange.com/questions/202/should-we-mac-then-encrypt-or-encrypt-then-mac
[2] https://security.stackexchange.com/questions/1873/whats-the-difference-between-mac-vs-hash
[3] https://crypto.stackexchange.com/questions/16428/why-is-plain-hash-then-encrypt-not-a-secure-mac
[4] https://blake2.net/blake2.pdf

**Comment by augustresende** [comment]
I think that is correct:

encrypt: https://github.com/AugustoResende/RaiLightWallet/blob/master/src/js/Wallet.js#L1131
```
var context = blake.blake2bInit(32);
    blake.blake2bUpdate(context, pack);
    checksum = blake.blake2bFinal(context);
    var salt = new Buffer(nacl.randomBytes(16));
    var key = pbkdf2.pbkdf2Sync(passPhrase, salt, iterations, 32, 'sha1');
    var options = { mode: AES.CBC, padding: Iso10126 };
    var encryptedBytes = AES.encrypt(pack, key, salt, options);
```

decrypt: https://github.com/AugustoResende/RaiLightWallet/blob/master/src/js/Wallet.js#L1150
```
var bytes = new Buffer(data, 'hex');
    checksum = bytes.slice(0, 32);
    var salt = bytes.slice(32, 48);
    var payload = bytes.slice(48);
    var key = pbkdf2.pbkdf2Sync(passPhrase, salt, iterations, 32, 'sha1');
    var options = {};
    options.padding = options.padding || Iso10126;
    var decryptedBytes = AES.decrypt(payload, key, salt, options);
    var context = blake.blake2bInit(32);
    blake.blake2bUpdate(context, decryptedBytes);
    var hash = (0, _functions.uint8_hex)(blake.blake2bFinal(context));
    if (hash != checksum.toString('hex').toUpperCase()) throw "Wallet is corrupted or has been tampered.";
```

**Comment by inkeliz** [comment]
The problems seems to be in:

     var context = blake.blake2bInit(32);

It's totally keyless. It need to be replaced with something like:

     var context = blake.blake2bInit(32, key);

It is mentioned here (https://www.npmjs.com/package/blakejs):

```
var KEY = null // optional key 
var OUTPUT_LENGTH = 64 // bytes 
var context = blake2bInit(OUTPUT_LENGTH, KEY)
```

The `key` need to be the same size of the hash, in this case 32 bytes. 

I think is possible to change the pbkdf2 (I don't like that, but anyway) to 64 bytes: 

    var key = pbkdf2.pbkdf2Sync(passPhrase, salt, iterations, 64, 'sha256');

This change make possible to use 32 bytes in the MAC (in the Blake2b), the last 32 bytes will be used in the AES.

**Comment by AugustoResende** [comment]
Can you do a pull request to fix this? I made no idea how to do...

**Comment by jaimehgb** [comment]
Interesting issue. I'm maintaining rai-wallet package, I guess I'll have to check that out.
Nice one @Inkeliz !

**Comment by augustresende** [comment]
@Inkeliz open your issue in this repo:

https://github.com/chriscohoat/rai-wallet

Soon RaiLightWallet will not use rai-wallet anymore.
