### ISSUE TITLE
No adress is created after clicking 'create new adress'

### ISSUE THREAD

**Issue by egonm12** [AugustoResende/RaiLightWallet#13]
Windows 10 Home, 64bit

Created a new wallet, but don't see an adress. 
I can't click on 'Send', 'Receive' or 'Settings' either.

![image](https://user-images.githubusercontent.com/20042349/34850212-3d4500d6-f725-11e7-8959-f92687374150.png)

**Comment by augustresende** [comment]
I can connect to your PC using TeamViewer? i need to see the logs

**Comment by egonm12** [comment]
@AugustoResende can I do this myself?

**Comment by augustresende** [comment]
@egonm12 try use the 0.2.1 release, please

**Comment by 8SecSleeper** [comment]
Same issue here.

**Comment by augustresende** [comment]
@10SecSleeper you tried use the 0.2.1 release?

**Comment by 8SecSleeper** [comment]
Link?

**Comment by AugustoResende** [comment]
same.

**Comment by augustresende** [comment]
https://github.com/AugustoResende/RaiLightWallet/releases

**Comment by 8SecSleeper** [comment]
Seems to be working. Send .00000001 or whatever to 

xrb_351wy76353aooba8ycoc7xt14a68ctn4csx5jxonzq79kofnyxambfuw1ykh

To test.

**Comment by AugustoResende** [comment]
I sent it in your wallet

**Comment by augustresende** [comment]
I sent!
