### ISSUE TITLE
Require the password (or 2FA) before sending each transaction

### ISSUE THREAD

**Issue by jaonoctus** [AugustoResende/RaiLightWallet#15]
I guess you need implement this on `keyFromAccount()` function:

https://github.com/AugustoResende/RaiLightWallet/blob/44eda48ca4916c820b70b66f603c8082e9d4389f/src/js/rai-wallet/functions.js#L453-L469

**Comment by augustresende** [comment]
You are wrong, is not in keyFromAccount..
